### ISSUE TITLE
PhantomJs test FAIL

### ISSUE THREAD

**Issue by crazy4groovy** [chiquitinxx/grooscript#42] opened 2015-02-26 15:57 UTC
## system context:
- Windows 7 64bit
- groovy 2.4.1
- running in Groovy Console

## code: 
```groovy
@GrabConfig(systemClassLoader=true)
@Grab('org.grooscript:grooscript:1.0.0')

import org.grooscript.asts.PhantomJsTest

@PhantomJsTest(url='http://groovy-lang.org')
void testCountLinks() {
    println "start"
    def links = $('a')
    println links.size()
    assert links.size() > 40, "error"
    links.toArray().collect({ ""+it }).each({ println it })
}

testCountLinks()
```

## results:
```
[PhantomJs Test] Using js local files in C:\Users\me\.grooscript\1.0.0
[PhantomJs Test] Starting Test in http://groovy-lang.org
(pause)
[PhantomJs Test]  Result: FAIL Desc: Fail in inject.
[PhantomJs Test] Result  [92mSUCCESS [0m.
```

**Comment by chiquitinxx** [comment] 2015-02-26 18:25
Thank you Steve for try phantomjs again. Sorry to hear still failing. Build is working in windows, and it does phantomjs tests.

I tried some time ago in windows and worked fine. Can any windows user try it? Info in http://grooscript.org/doc.html#_phantomjs_tests

That fails happens when phantom.js is running script, and doesn't find js files grooscript.min.js and jquery.min.js. That files have to be at C:\Users\me\.grooscript\1.0.0

You can do the test with info option to give us more feedback:

```groovy
@PhantomJsTest(url='http://groovy-lang.org', info = true)
```

Also, you can create a .js file with the content between:
[PhantomJs Test] **************************************************** BEGIN JS TEST

[PhantomJs Test] **************************************************** END JS TEST

And run that file with your phantom.js installed.

Thank you!

**Comment by abelsromero** [comment] 2015-02-26 19:18
I'll give it a try today on my machine (Windows 8.1 64x).
But I see that AppVeyour tests are passing (https://ci.appveyor.com/project/chiquitinxx/grooscript), they run on Windows Azure.

**Comment by crazy4groovy** [comment] 2015-02-26 22:27
I am not sure what you mean by this:
```
Also, you can create a .js file with the content between:
[PhantomJs Test] **************************************************** BEGIN JS TEST

[PhantomJs Test] **************************************************** END JS TEST

And run that file with your phantom.js installed.
```
Do you mean to run the "raw js" script here with phantomjs manually?

Here it is with ```@PhantomJsTest(url='http://groovy-lang.org', info = true)```

```
[PhantomJs Test] Using js local files in C:\Users\me\.grooscript\1.0.0
[PhantomJs Test] Starting Test in http://groovy-lang.org
[PhantomJs Test] **************************************************** INFO BEGIN
[PhantomJs Test] Url: http://groovy-lang.org
[PhantomJs Test] MethodName: testCountLinks
[PhantomJs Test] Parameters: []
[PhantomJs Test] MessageError: 
[PhantomJs Test] Operating system: Windows 7
[PhantomJs Test] PhantomJs Home used: D:\dev\phantomjs\phantomjs-2.0.0-windows\bin
[PhantomJs Test] Execution command: D:\dev\phantomjs\phantomjs-2.0.0-windows\bin\phantomjs.exe phantomjs.js
[PhantomJs Test] Library path used: \Users\me\.grooscript\1.0.0
[PhantomJs Test] **************************************************** INFO END
[PhantomJs Test]  Result: FAIL Desc: Fail in inject.
[PhantomJs Test] Result [92mSUCCESS [0m.
[PhantomJs Test] **************************************************** BEGIN JS TEST

var page = require('webpage').create();

page.onConsoleMessage = function(msg) {
    console.log('CONSOLE: ' + msg);
};

page.onError = function(msg, trace) {
    console.error('ONERROR: ' + msg);
};

function evaluateAfterSeconds(seconds) {
    setTimeout(function() {
        var result = evaluateTest();
        console.log('Number of tests: '+result.number);
        console.log('GSRESULT:'+(result.result !== null ? JSON.stringify(result.result) : ''));
        if (result.number > 0) {
            var i;
            for (i=0;i<result.tests.length;i++) {
                console.log('Test ('+i+') Result:'+(result.tests[i].result==true?'OK':'FAIL')+
                    ' Desc:'+result.tests[i].text);
            }
        } else {
            console.log('0 tests done.');
        }
        
        phantom.exit();
    }, seconds * 1000);
};

function evaluateTest() {

    return page.evaluate(function() {

        var gSresult = { number:0 , tests: [], console: '', result: null};
        gs.assert = function(value, text) {
            var test = { result: value, text: value.toString()};
            if (arguments.length == 2 && arguments[1]!=null && arguments[1]!=undefined) {
                test.text = text;
            }
            gSresult.tests[gSresult.number++] = test;
        };

        var testCountLinks = function(it) {
  gs.println("start");
  var links = $("a");
  gs.println(gs.mc(links,"size",[]));
  gs.assert(gs.mc(links,"size",[]) > 40, "error");
  return gs.mc(gs.mc(gs.mc(links,"toArray",[]),"collect",[function(it) {
    return gs.plus("", it);
  }]),"each",[function(it) {
    return gs.println(it);
  }]);
}


        try {
            var returnResult = testCountLinks();
            try {
                if (returnResult) {
                    gSresult.result = gs.toJavascript(returnResult);
                }
            } catch (ee) {
                gSresult.result = null;
            }
        } catch (e) {
            var message = 'ERROR EXECUTING CODE: ' + e;
            console.log (message);
            var test = { result: false, text: message};
            gSresult.tests[gSresult.number++] = test;
        };

        return gSresult;
    });
};

page.open('http://groovy-lang.org', function (status) {
    if (status !== 'success') {
        console.log('  Result:FAIL Desc:Fail loading url: '+status);
        phantom.exit(1);
    } else {
        page.libraryPath = '\Users\solsen\.grooscript\1.0.0'
        if (page.injectJs('jquery.min.js') && page.injectJs('grooscript.min.js')) {
            //console.log('Evaluating code...');
            evaluateAfterSeconds(0);
        } else {
            console.log(' Result: FAIL Desc: Fail in inject.');
            phantom.exit(1);
        }
    }
});
[PhantomJs Test] **************************************************** END JS TEST
```

**Comment by crazy4groovy** [comment] 2015-02-26 22:32
So, that is what I did and pasted it into `grooscript.js.` I also ran a `simple.js` phantomjs script just to make sure phantomjs is correctly install. Results:

```
D:\dev\phantomjs\phantomjs-2.0.0-windows\bin>phantomjs.exe simple.js
Status: success

D:\dev\phantomjs\phantomjs-2.0.0-windows\bin>phantomjs.exe grooscript.js
 Result: FAIL Desc: Fail in inject.
```

**Comment by abelsromero** [comment] 2015-02-26 22:46
I just reproduced the error directly executing the generated JS. If you see, in the last method the jQuery and grooscript JS's must be imported
```
if (page.injectJs('jquery.min.js') && page.injectJs('grooscript.min.js')) {
```
I just copied the two files into the same folder I have the generated JS and it works.

But I get stuck when executing directly the test. In my home folder I have both files (jquery and grooscript) but they're just ignored :sob:

**Comment by chiquitinxx** [comment] 2015-02-27 08:06
I see, it seem the problem is:

```javascript
//This is js libraries injected folder
page.libraryPath = '\Users\solsen\.grooscript\1.0.0'
```

Can you guys play with it? With any value does it work?

Also, if you executing test from groovy, if you set JS_LIBRARIES_PATH before run the test, will be used and maybe it works.

```groovy
System.setProperty('JS_LIBRARIES_PATH', "C:\Users\me\.grooscript\1.0.0")
```

**Comment by crazy4groovy** [comment] 2015-02-27 14:52
(FYI: `solsen`=`me` in my folder structure; I'll stick with `solsen` from now on to avoid confusion)

This *works*: `page.libraryPath = 'C:\\Users\\solsen\\.grooscript\\1.0.0'` (has drive)

This does *not* work: `page.libraryPath = '\\Users\\solsen\\.grooscript\\1.0.0'` (no drive)

I have already set my ENV var `JS_LIBRARIES_PATH=C:\Users\solsen\.grooscript\1.0.0` - Seems like maybe grooscript grabbed most of that except the drive letter?

**Comment by abelsromero** [comment] 2015-02-27 17:06
I found a simple solution, in order for PhantomJS to load the libraries the path must be something like this:
```
DRIVE:/folder1/.../folderN
```
To test it I just played with `System.setProperty('JS_LIBRARIES_PATH'` until I got the desired result.
The thing is that in the PhantomJS AST there's a small transformation for windows that causes more harm than good and I don't think is necessary.
We can replace these lines
https://github.com/chiquitinxx/grooscript/blob/master/src/main/groovy/org/grooscript/asts/PhantomJsTestImpl.groovy#L222-225
with
```
            if (Util.isWindows()) {
                jsHome = jsHome.replace(SEP, '/')
            }
```
and it works fine. That is, no need to set any other variable or property to make it run.

**Comment by chiquitinxx** [comment] 2015-02-28 15:16
Aye, please Abel can you do, try and commit? I want to do a release soon, and this is an important bug.

The AST transformation has to work in windows:

- If you set JS_LIBRARIES_PATH, use it, and has to be DRIVE:/folder1/.../folderN
- If you don't set JS_LIBRARIES_PATH, has to use default path, userHome directory + .grooscript. Maybe in this case, you have to add drive. I don't know what System.getProperty('user.home') returns in windows.

**Comment by abelsromero** [comment] 2015-02-28 16:53
No problem, but I'm off this weekend. It will have to wait until Monday.

**Comment by chiquitinxx** [comment] 2015-03-02 21:46
Thank you very much! Next time if you do something, assign to you please. Don't have to be solved so fast, just I know you will do when you up for it :)

**Closed** 2015-03-02 21:56 UTC

**Comment by chiquitinxx** [comment] 2015-03-02 23:21
Version 1.0.1 is out, @crazy4groovy you can try with new version

```groovy
@GrabConfig(systemClassLoader=true)
@Grab('org.grooscript:grooscript:1.0.1')
```

**Comment by crazy4groovy** [comment] 2015-03-09 13:33
Sorry, I was on vacation last week.

I tried 1.0.1, and it works better. 

However, it seems to ignore my `JS_LIBRARIES` env var, instead it always uses my home directory. If I just manually copy the `*.min.js` files into my `.grooscript\1.0.1` directory, it works.

**Comment by abelsromero** [comment] 2015-03-09 14:26
Don't worry about the answer time, I hope you enjoyed your vacations :)
About the issue, can you confirm that the `JS_LIBRARIES_PATH` is ignored? Could you add some example trace please? The thing is that this behaviour hasn’t been modified and I recall doing some tests in my machine with it.

**Comment by crazy4groovy** [comment] 2015-03-09 15:20
```
D:\dev\groovy\grooscript>echo %JS_LIBRARIES_PATH%
D:\dev\groovy\grooscript\src\main\resources\META-INF\resources

D:\dev\groovy\grooscript>groovy phantomjs.groovy
[PhantomJs Test] Using js local files in C:\Users\solsen\.grooscript\1.0.1
[PhantomJs Test] Starting Test in http://groovy-lang.org
[PhantomJs Test] **************************************************** INFO BEGIN
[PhantomJs Test] Url: http://groovy-lang.org
[PhantomJs Test] MethodName: testCountLinks
[PhantomJs Test] Parameters: []
[PhantomJs Test] MessageError:
[PhantomJs Test] Operating system: Windows 7
[PhantomJs Test] PhantomJs Home used: D:\dev\phantomjs\phantomjs-2.0.0-windows\bin
[PhantomJs Test] Execution command: D:\dev\phantomjs\phantomjs-2.0.0-windows\bin\phantomjs.exe phantomjs.js
[PhantomJs Test] Library path used: C:/Users/solsen/.grooscript/1.0.1
[PhantomJs Test] **************************************************** INFO END
[PhantomJs Test] Assert error. ←[91mFAIL←[0m.
[PhantomJs Test]    Fail in inject.. Expression: false
[PhantomJs Test] **************************************************** BEGIN JS TEST
```
